system:
  backendURL: http://localhost:8080
  frontendURL: http://localhost:5173
mailInfoCustom:
  verifyResetPasswordFrontEndPoint: /auth/reset-password
  loginFrontEndPoint: /auth/login
info:
  dentistName: Ronial Doctor
  hotline: 0392477615
  dentistEmail: dungtna.22itb@vku.udn.vn
server:
  port: 8080
mailer:
  host: smtp.gmail.com
  port: 587
  username: ron19102004@gmail.com
  password: yolinxdflfxnkcuc
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true
redis:
  host: localhost
  port: 6379
  keys:
    reward-all: reward:all
    specialize-all: specialize:all
    service-all : service:all
spring:
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: Hospital-BE
  datasource:
    url: jdbc:mysql://localhost:3306/prj4ron?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  key-path:
    access-token-private-path: keys/access-token-private.key
    access-token-public-path: keys/access-token-public.key
    refresh-token-private-path: keys/refresh-token-private.key
    refresh-token-public-path: keys/refresh-token-public.key
